"""Ingest a local repository: walk, chunk, embed, persist.

Usage:
    python -m apps.workers.ingestion /path/to/repo --name my-repo

This is the production ingestion path. It writes to Postgres.
For a dry run that prints stats only, pass --dry-run.
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import sys
import time
from collections import Counter
from pathlib import Path
from uuid import UUID

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from packages.core import db
from packages.core.chunking.base import Chunk
from packages.core.chunking.python_chunker import PythonChunker
from packages.core.chunking.splitter import split_oversize
from packages.core.chunking.walker import WalkedFile, walk_repo
from packages.core.llm.embeddings import EmbeddingClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("ingestion")

CHUNKERS = {"python": PythonChunker()}


# ---------- DB helpers ----------

async def _create_repo(name: str, source_path: str) -> UUID:
    """Create a repos row in 'indexing' state and return its id."""
    repo_id = await db.fetchval(
        """
        INSERT INTO repos (name, source_url, status)
        VALUES ($1, $2, 'indexing')
        RETURNING id
        """,
        name, source_path,
    )
    return repo_id


async def _mark_repo(repo_id: UUID, status: str) -> None:
    await db.execute("UPDATE repos SET status = $1 WHERE id = $2", status, repo_id)


async def _insert_file(repo_id: UUID, walked: WalkedFile) -> UUID:
    file_id = await db.fetchval(
        """
        INSERT INTO files (repo_id, path, language, loc)
        VALUES ($1, $2, $3, $4)
        RETURNING id
        """,
        repo_id,
        str(walked.relative_path),
        walked.language,
        walked.source.count(b"\n") + 1,
    )
    return file_id


async def _insert_chunks(
    repo_id: UUID,
    file_id: UUID,
    chunks: list[Chunk],
    embeddings: list[list[float]],
) -> None:
    """Bulk-insert chunks. content_tsv is generated by Postgres automatically."""
    rows = [
        (
            file_id,
            repo_id,
            c.symbol_name,
            c.symbol_kind,
            c.start_line,
            c.end_line,
            c.imports,
            c.content,
            embedding,
        )
        for c, embedding in zip(chunks, embeddings)
    ]
    await db.executemany(
        """
        INSERT INTO chunks
            (file_id, repo_id, symbol_name, symbol_kind,
             start_line, end_line, imports, content, embedding)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        """,
        rows,
    )


# ---------- main pipeline ----------

async def ingest(repo_path: Path, name: str, *, dry_run: bool = False) -> None:
    t_start = time.perf_counter()

    if not dry_run:
        repo_id = await _create_repo(name=name, source_path=str(repo_path))
        log.info("created repo %s (%s)", name, repo_id)
    else:
        repo_id = None

    embedder = EmbeddingClient() if not dry_run else None

    files_chunked = 0
    total_chunks = 0
    kinds: Counter[str] = Counter()

    try:
        for walked in walk_repo(repo_path):
            chunker = CHUNKERS.get(walked.language)
            if chunker is None:
                continue

            chunks = split_oversize(chunker.chunk(walked.source))
            if not chunks:
                continue

            files_chunked += 1
            total_chunks += len(chunks)
            for c in chunks:
                kinds[c.symbol_kind] += 1

            if dry_run:
                continue

            # Embed and persist
            file_id = await _insert_file(repo_id, walked)
            embeddings = embedder.embed([c.content for c in chunks])
            await _insert_chunks(repo_id, file_id, chunks, embeddings)

            log.info(
                "%s -> %d chunks (%d total)",
                walked.relative_path, len(chunks), total_chunks,
            )

    except Exception:
        if repo_id is not None:
            await _mark_repo(repo_id, "failed")
        raise

    if repo_id is not None:
        await _mark_repo(repo_id, "ready")

    elapsed = time.perf_counter() - t_start
    log.info(
        "done: %d files, %d chunks in %.1fs (%s)",
        files_chunked, total_chunks, elapsed, dict(kinds),
    )


def main() -> int:
    p = argparse.ArgumentParser(description="Ingest a local repository.")
    p.add_argument("path", type=Path, help="path to a local repository")
    p.add_argument("--name", required=True, help="display name for this repo")
    p.add_argument("--dry-run", action="store_true", help="don't write to DB")
    args = p.parse_args()

    if not args.path.exists():
        print(f"error: {args.path} does not exist", file=sys.stderr)
        return 1

    try:
        asyncio.run(_run(args.path, args.name, args.dry_run))
    except KeyboardInterrupt:
        print("\ninterrupted", file=sys.stderr)
        return 130
    return 0


async def _run(path: Path, name: str, dry_run: bool) -> None:
    try:
        await ingest(path, name, dry_run=dry_run)
    finally:
        await db.close_pool()


if __name__ == "__main__":
    raise SystemExit(main())
